### PR TITLE
unzip inside a root folder

### LINKED ISSUE #31: Unzipping drops all the files in the current directory
Suggestion: it would be ideal if the files were unzipped into their own directory instead of being dropped in the current directory among other files.

### PR DESCRIPTION
**Pull request by siddhi523**
resolved #31 
Output:  
image

### CODE REVIEW

**Comment by tsl143** [comment]
Instead of changing at every places you can modify `zip` object here - https://github.com/web-ext-labs/ui-tool/blob/master/src/createManifest.js#L6

**Review by tsl143 — CHANGES_REQUESTED** [review]
Instead of changing at every places you can modify zip object here - https://github.com/web-ext-labs/ui-tool/blob/master/src/createManifest.js#L6

**Comment by siddhi523** [comment]
Yes thanks, will do it asap

**Comment by siddhi523** [comment]
const zip = (new JSZip()).folder(manifestJson.name)
@tsl143 I tried it but this isn't solving the issue

**Review by tsl143 — APPROVED** [review]

**Comment by tsl143** [comment]
Thanks for the PR @siddhi523 💯

**Comment by championshuttler** [comment]
Thanks for the contribution @siddhi523 🎉

**Pull request merged**
